#!/usr/bin/env node
// Regenerate src/cljc/open_hax/website/data/assets.cljc FROM WHAT WAS STAGED.
//
// The scan walks the build output directory, never the source library, so the
// generated manifest cannot claim an asset the build did not produce. Run
// scripts/stage-assets.mjs first; `pnpm build` runs both in order.
//
// Zero staged assets produces two empty vectors. That is a valid build.

import { existsSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

import {
  siteOutDir,
  assetsManifestPath,
  graphicsExtensions,
  musicExtensions,
  stableId,
  repoRoot,
} from './asset-config.mjs';

function scan(subdir, pattern) {
  const root = join(siteOutDir, subdir);
  if (!existsSync(root)) return [];
  const found = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile() && pattern.test(entry.name)) {
        const rel = relative(root, full).split('\\').join('/');
        // Encode per segment: real filenames in this library carry spaces and
        // parentheses, and an unencoded one produces a src the browser has to
        // guess at.
        const encoded = rel.split('/').map(encodeURIComponent).join('/');
        found.push({
          src: `/${subdir}/${encoded}`,
          name: entry.name.replace(/\.[^.]+$/, ''),
          folder: dirname(rel) === '.' ? 'root' : dirname(rel),
        });
      }
    }
  };
  walk(root);
  found.sort((a, b) => a.src.localeCompare(b.src));
  return found;
}

function escape(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

const graphics = scan('graphics', graphicsExtensions);
const music = scan('music', musicExtensions);

const header = `(ns open-hax.website.data.assets
  "Gallery manifest, GENERATED by scripts/scan-assets.mjs. Do not edit.

  Generated from the assets the build actually staged into the output
  directory, never from a source library, so every :src here resolves inside
  the published artifact. Empty vectors are a valid state: with no asset roots
  configured the galleries render empty and their count sentences read 0.

  Asset titles, categories and folder names are derived from filenames and are
  NOT editorial copy — they are not translated and never enter the locale
  dictionaries.")

`;

let out = header;
out += '(def graphics\n  [';
for (const g of graphics) {
  out += `\n   {:id ${stableId(g.src)} :title "${escape(g.name)}" :category "${escape(g.folder)}" :src "${escape(g.src)}"}`;
}
out += graphics.length ? '\n   ])\n\n' : '])\n\n';

out += '(def music\n  [';
for (const m of music) {
  out += `\n   {:id ${stableId(m.src)} :title "${escape(m.name.replace(/_/g, ' '))}" :artist "OpenHax" :folder "${escape(m.folder)}" :duration "--:--" :src "${escape(m.src)}"}`;
}
out += music.length ? '\n   ])\n' : '])\n';

mkdirSync(dirname(assetsManifestPath), { recursive: true });
writeFileSync(assetsManifestPath, out, 'utf8');

console.log(
  `generated ${relative(repoRoot, assetsManifestPath)}: ` +
    `${graphics.length} graphics, ${music.length} music (from ${relative(repoRoot, siteOutDir)})`,
);
