(ns open-hax.website.data.assets
  "Gallery manifest, GENERATED by scripts/scan-assets.mjs. Do not edit.

  Generated from the assets the build actually staged into the output
  directory, never from a source library, so every :src here resolves inside
  the published artifact. Empty vectors are a valid state: with no asset roots
  configured the galleries render empty and their count sentences read 0.

  Asset titles, categories and folder names are derived from filenames and are
  NOT editorial copy — they are not translated and never enter the locale
  dictionaries.")

(def graphics
  [])

(def music
  [])
